server:
  port: 6688

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbps?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: mbps
    password: mbps@Z112801

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zephyr.mpbsapp.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO

jwt:
  secret: mbpsSecretKeyHere
  expiration: 3600000